### ISSUE TITLE
Can the events made to be clickable?

### ISSUE THREAD

**Issue by stoan** [0xdv/vue-timeline-component#19]
Hello,

I'm new to front-end development and vue.js, I would like to use this component. I wanted to find out if it's possible to add a click event on each Event, So I can open something like a dialog window

Regards

**Comment by 0xdv** [comment]
Hi! Yep, should be easy to add. I'll review it soon)

**Comment by 0xdv** [comment]
Hi @stoan 
I added click handler for events.
Check out it on this [demo](https://github.com/0xdv/vue-timeline-component/commit/439901e72671ce0dee0b42570110f03b30d9cd54#diff-b04b38d4e36f7a7171aeb211bf933eaf36d41d9866ebbc3639f673f84dc350ae)

Regards

**Comment by stoan** [comment]
Hello,

Thank you for the fast add. 

I will try this out. 

You are awesome!
